[package]
name = "verifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggst-api = { git = "https://github.com/xynxynxyn/ggst-api-rs" }
